"""
Asana integration model.

One row per organization. api_token is Fernet-encrypted via encrypt_api_key
(never stored plaintext). Encryption happens in the route layer, not here.
See src/utils/encryption.py.

Asana auth is a Bearer Personal Access Token against the fixed host
https://app.asana.com/api/1.0 — unlike Jira/Zendesk there is no per-org
site_url/subdomain and no separate email field.
"""
import sqlalchemy as sa
from sqlalchemy import Column, Integer, String, Text, Boolean, DateTime, ForeignKey, Index, UniqueConstraint, JSON
from datetime import datetime
from .base import Base


class AsanaIntegration(Base):
    """Org-wide Asana connection (Personal Access Token, Bearer auth). One row per org."""
    __tablename__ = "asana_integrations"

    id = Column(Integer, primary_key=True, index=True)
    organization_id = Column(Integer, ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False)
    api_token = Column(Text, nullable=False)  # Fernet-encrypted via encrypt_api_key (route-layer concern)
    token_hint = Column(String(8), nullable=True)  # last chars of plaintext, e.g. "...abcd"
    account_gid = Column(String(255), nullable=True)  # from GET /users/me
    display_name = Column(String(255), nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
    connected_by_user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    connected_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    last_synced_at = Column(DateTime, nullable=True)
    last_sync_status = Column(String(50), nullable=True)
    last_error = Column(Text, nullable=True)
    status_sync_enabled = Column(Boolean, nullable=False, default=False, server_default=sa.false())
    status_mapping = Column(JSON, nullable=True)  # {category_key: rereflect_status}, e.g. {"done": "resolved"}
    # asana-webhook aspect (status-sync-realtime-mapping): inbound real-time
    # webhook. webhook_secret is the Asana-issued handshake secret (Text,
    # Fernet-encrypted at the route/receiver layer -- NULL means the webhook
    # has not completed its handshake, fail-closed -- see
    # src/api/routes/asana_webhook.py). webhook_gid is the Asana webhook gid
    # returned by POST /webhooks (used to delete the webhook at Asana on
    # disable). Unlike Jira's operator-supplied secret, Asana's secret is
    # captured on first delivery (the handshake), not generated by us.
    webhook_secret = Column(Text, nullable=True)
    webhook_gid = Column(String(255), nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    __table_args__ = (
        UniqueConstraint('organization_id', name='uq_asana_integrations_org_id'),
        Index('ix_asana_integrations_org_id', 'organization_id'),
    )

    def __repr__(self):
        return f"<AsanaIntegration(id={self.id}, org={self.organization_id}, active={self.is_active})>"


class FeedbackAsanaTask(Base):
    """Links feedback items to Asana tasks."""
    __tablename__ = "feedback_asana_tasks"

    id = Column(Integer, primary_key=True, index=True)
    organization_id = Column(Integer, ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False)
    feedback_id = Column(Integer, ForeignKey("feedback_items.id", ondelete="CASCADE"), nullable=False)
    asana_task_gid = Column(String(255), nullable=False)   # Asana task gid, e.g. "1201234567890"
    asana_task_url = Column(Text, nullable=False)
    asana_task_name = Column(String(500), nullable=False)
    created_by_user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    asana_completed = Column(Boolean, nullable=True)          # Asana task.completed
    asana_status_category = Column(String(20), nullable=True) # core category: new/done (fwd-compat: indeterminate)
    last_status_synced_at = Column(DateTime, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index('ix_feedback_asana_tasks_org_id', 'organization_id'),
        Index('ix_feedback_asana_tasks_feedback_id', 'feedback_id'),
    )

    def __repr__(self):
        return f"<FeedbackAsanaTask(id={self.id}, feedback={self.feedback_id}, task='{self.asana_task_gid}')>"
