"""add_linear_integration_tables

Revision ID: 5ee1b2567a02
Revises: n3o4p5q6r7s8
Create Date: 2026-03-08 02:15:55.284090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ee1b2567a02'
down_revision: Union[str, None] = 'n3o4p5q6r7s8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linear_status_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('linear_status_name', sa.String(length=255), nullable=False),
    sa.Column('linear_status_type', sa.String(length=50), nullable=False),
    sa.Column('rereflect_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linear_status_mappings_id'), 'linear_status_mappings', ['id'], unique=False)
    op.create_index('ix_linear_status_mappings_org_type', 'linear_status_mappings', ['organization_id', 'linear_status_type'], unique=False)
    op.create_table('linear_team_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('rereflect_category', sa.String(length=100), nullable=False),
    sa.Column('linear_team_id', sa.String(length=255), nullable=False),
    sa.Column('linear_team_name', sa.String(length=255), nullable=False),
    sa.Column('linear_project_id', sa.String(length=255), nullable=True),
    sa.Column('linear_project_name', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linear_team_mappings_id'), 'linear_team_mappings', ['id'], unique=False)
    op.create_index('ix_linear_team_mappings_org_category', 'linear_team_mappings', ['organization_id', 'rereflect_category'], unique=False)
    op.create_table('linear_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('linear_org_id', sa.String(length=255), nullable=False),
    sa.Column('linear_org_name', sa.String(length=255), nullable=False),
    sa.Column('connected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('webhook_secret', sa.String(length=255), nullable=False),
    sa.Column('webhook_id', sa.String(length=255), server_default='', nullable=False),
    sa.Column('issue_title_template', sa.Text(), nullable=True),
    sa.Column('issue_description_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_linear_integrations_org_id')
    )
    op.create_index(op.f('ix_linear_integrations_id'), 'linear_integrations', ['id'], unique=False)
    op.create_index('ix_linear_integrations_org_id', 'linear_integrations', ['organization_id'], unique=False)
    op.create_table('feedback_linear_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('linear_issue_id', sa.String(length=255), nullable=False),
    sa.Column('linear_issue_identifier', sa.String(length=50), nullable=False),
    sa.Column('linear_issue_url', sa.Text(), nullable=False),
    sa.Column('linear_issue_title', sa.String(length=500), nullable=False),
    sa.Column('linear_status', sa.String(length=255), nullable=True),
    sa.Column('linear_assignee', sa.String(length=255), nullable=True),
    sa.Column('linear_priority', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_linear_issues_feedback_id', 'feedback_linear_issues', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_feedback_linear_issues_id'), 'feedback_linear_issues', ['id'], unique=False)
    op.create_index('ix_feedback_linear_issues_linear_issue_id', 'feedback_linear_issues', ['linear_issue_id'], unique=False)
    op.create_index('ix_feedback_linear_issues_org_id', 'feedback_linear_issues', ['organization_id'], unique=False)
    op.alter_column('conversation_folders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_conversation_folders_id'), 'conversation_folders', ['id'], unique=False)
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_schema_whitelist_id'), 'copilot_schema_whitelist', ['id'], unique=False)
    op.alter_column('llm_model_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_llm_model_prices_id'), 'llm_model_prices', ['id'], unique=False)
    op.alter_column('llm_usage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_llm_usage_logs_id'), 'llm_usage_logs', ['id'], unique=False)
    op.alter_column('org_ai_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('org_ai_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_org_ai_config_id'), 'org_ai_config', ['id'], unique=False)
    op.alter_column('org_api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('org_api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_org_api_keys_id'), 'org_api_keys', ['id'], unique=False)
    op.alter_column('query_template_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_query_template_mappings_id'), 'query_template_mappings', ['id'], unique=False)
    op.alter_column('query_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('query_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_query_templates_id'), 'query_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_templates_id'), table_name='query_templates')
    op.alter_column('query_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('query_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_query_template_mappings_id'), table_name='query_template_mappings')
    op.alter_column('query_template_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_org_api_keys_id'), table_name='org_api_keys')
    op.alter_column('org_api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('org_api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_org_ai_config_id'), table_name='org_ai_config')
    op.alter_column('org_ai_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('org_ai_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_llm_usage_logs_id'), table_name='llm_usage_logs')
    op.alter_column('llm_usage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_llm_model_prices_id'), table_name='llm_model_prices')
    op.alter_column('llm_model_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_copilot_schema_whitelist_id'), table_name='copilot_schema_whitelist')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_conversation_folders_id'), table_name='conversation_folders')
    op.alter_column('conversation_folders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_feedback_linear_issues_org_id', table_name='feedback_linear_issues')
    op.drop_index('ix_feedback_linear_issues_linear_issue_id', table_name='feedback_linear_issues')
    op.drop_index(op.f('ix_feedback_linear_issues_id'), table_name='feedback_linear_issues')
    op.drop_index('ix_feedback_linear_issues_feedback_id', table_name='feedback_linear_issues')
    op.drop_table('feedback_linear_issues')
    op.drop_index('ix_linear_integrations_org_id', table_name='linear_integrations')
    op.drop_index(op.f('ix_linear_integrations_id'), table_name='linear_integrations')
    op.drop_table('linear_integrations')
    op.drop_index('ix_linear_team_mappings_org_category', table_name='linear_team_mappings')
    op.drop_index(op.f('ix_linear_team_mappings_id'), table_name='linear_team_mappings')
    op.drop_table('linear_team_mappings')
    op.drop_index('ix_linear_status_mappings_org_type', table_name='linear_status_mappings')
    op.drop_index(op.f('ix_linear_status_mappings_id'), table_name='linear_status_mappings')
    op.drop_table('linear_status_mappings')
    # ### end Alembic commands ###
