"""add_churn_risk_factors_and_confidence_score

Revision ID: 6e4501930bf0
Revises: g0h1i2j3k4l5
Create Date: 2026-02-21 02:07:21.189405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4501930bf0'
down_revision: Union[str, None] = 'g0h1i2j3k4l5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customer_analysis_actions_id'), 'customer_analysis_actions', ['id'], unique=False)
    op.create_index(op.f('ix_customer_health_history_id'), 'customer_health_history', ['id'], unique=False)
    op.add_column('customer_health_scores', sa.Column('confidence_score', sa.Integer(), nullable=True))
    op.alter_column('customer_health_scores', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_customer_health_scores_id'), 'customer_health_scores', ['id'], unique=False)
    op.add_column('feedback_items', sa.Column('churn_risk_factors', sa.JSON(), nullable=True))
    op.drop_index('ix_feedback_customer_email', table_name='feedback_items')
    op.create_index(op.f('ix_feedback_items_customer_email'), 'feedback_items', ['customer_email'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_saved_views_id'), 'saved_views', ['id'], unique=False)
    op.create_index(op.f('ix_shared_links_id'), 'shared_links', ['id'], unique=False)
    op.drop_constraint('slack_alert_logs_feedback_id_fkey', 'slack_alert_logs', type_='foreignkey')
    op.create_foreign_key(None, 'slack_alert_logs', 'feedback_items', ['feedback_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_user_alert_preferences_id'), 'user_alert_preferences', ['id'], unique=False)
    op.drop_constraint('users_invited_by_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['invited_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_invited_by_id_fkey', 'users', 'users', ['invited_by_id'], ['id'])
    op.drop_index(op.f('ix_user_alert_preferences_id'), table_name='user_alert_preferences')
    op.drop_constraint(None, 'slack_alert_logs', type_='foreignkey')
    op.create_foreign_key('slack_alert_logs_feedback_id_fkey', 'slack_alert_logs', 'feedback_items', ['feedback_id'], ['id'])
    op.drop_index(op.f('ix_shared_links_id'), table_name='shared_links')
    op.drop_index(op.f('ix_saved_views_id'), table_name='saved_views')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_feedback_items_customer_email'), table_name='feedback_items')
    op.create_index('ix_feedback_customer_email', 'feedback_items', ['customer_email'], unique=False)
    op.drop_column('feedback_items', 'churn_risk_factors')
    op.drop_index(op.f('ix_customer_health_scores_id'), table_name='customer_health_scores')
    op.alter_column('customer_health_scores', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('customer_health_scores', 'confidence_score')
    op.drop_index(op.f('ix_customer_health_history_id'), table_name='customer_health_history')
    op.drop_index(op.f('ix_customer_analysis_actions_id'), table_name='customer_analysis_actions')
    # ### end Alembic commands ###
